# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class BroadcastStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Enviar = channel.stream_unary(
        '/chatsito.Broadcast/Enviar',
        request_serializer=chat__pb2.Mensaje.SerializeToString,
        response_deserializer=chat__pb2.Confirmacion.FromString,
        )
    self.Recibir = channel.unary_stream(
        '/chatsito.Broadcast/Recibir',
        request_serializer=chat__pb2.Usuario.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.Conectar = channel.unary_unary(
        '/chatsito.Broadcast/Conectar',
        request_serializer=chat__pb2.Usuario.SerializeToString,
        response_deserializer=chat__pb2.Confirmacion.FromString,
        )
    self.Conectados = channel.unary_unary(
        '/chatsito.Broadcast/Conectados',
        request_serializer=chat__pb2.Mensaje.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.Enviados = channel.unary_stream(
        '/chatsito.Broadcast/Enviados',
        request_serializer=chat__pb2.Usuario.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.Desconectar = channel.unary_unary(
        '/chatsito.Broadcast/Desconectar',
        request_serializer=chat__pb2.Usuario.SerializeToString,
        response_deserializer=chat__pb2.Confirmacion.FromString,
        )


class BroadcastServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Enviar(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Recibir(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Conectar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Conectados(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Enviados(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Desconectar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BroadcastServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Enviar': grpc.stream_unary_rpc_method_handler(
          servicer.Enviar,
          request_deserializer=chat__pb2.Mensaje.FromString,
          response_serializer=chat__pb2.Confirmacion.SerializeToString,
      ),
      'Recibir': grpc.unary_stream_rpc_method_handler(
          servicer.Recibir,
          request_deserializer=chat__pb2.Usuario.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'Conectar': grpc.unary_unary_rpc_method_handler(
          servicer.Conectar,
          request_deserializer=chat__pb2.Usuario.FromString,
          response_serializer=chat__pb2.Confirmacion.SerializeToString,
      ),
      'Conectados': grpc.unary_unary_rpc_method_handler(
          servicer.Conectados,
          request_deserializer=chat__pb2.Mensaje.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'Enviados': grpc.unary_stream_rpc_method_handler(
          servicer.Enviados,
          request_deserializer=chat__pb2.Usuario.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'Desconectar': grpc.unary_unary_rpc_method_handler(
          servicer.Desconectar,
          request_deserializer=chat__pb2.Usuario.FromString,
          response_serializer=chat__pb2.Confirmacion.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chatsito.Broadcast', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
