# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chatsito',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\x12\x08\x63hatsito\"\x15\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\"J\n\x07Mensaje\x12\r\n\x05id_em\x18\x01 \x01(\t\x12\r\n\x05id_re\x18\x02 \x01(\t\x12\x0e\n\x06\x63uerpo\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x1b\n\x0c\x43onfirmacion\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xce\x02\n\tBroadcast\x12\x35\n\x06\x45nviar\x12\x11.chatsito.Mensaje\x1a\x16.chatsito.Confirmacion(\x01\x12\x31\n\x07Recibir\x12\x11.chatsito.Usuario\x1a\x11.chatsito.Mensaje0\x01\x12\x35\n\x08\x43onectar\x12\x11.chatsito.Usuario\x1a\x16.chatsito.Confirmacion\x12\x32\n\nConectados\x12\x11.chatsito.Mensaje\x1a\x11.chatsito.Mensaje\x12\x32\n\x08\x45nviados\x12\x11.chatsito.Usuario\x1a\x11.chatsito.Mensaje0\x01\x12\x38\n\x0b\x44\x65sconectar\x12\x11.chatsito.Usuario\x1a\x16.chatsito.Confirmacionb\x06proto3')
)




_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='chatsito.Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chatsito.Usuario.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='chatsito.Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_em', full_name='chatsito.Mensaje.id_em', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_re', full_name='chatsito.Mensaje.id_re', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cuerpo', full_name='chatsito.Mensaje.cuerpo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='chatsito.Mensaje.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=121,
)


_CONFIRMACION = _descriptor.Descriptor(
  name='Confirmacion',
  full_name='chatsito.Confirmacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='chatsito.Confirmacion.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=150,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='chatsito.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
DESCRIPTOR.message_types_by_name['Confirmacion'] = _CONFIRMACION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), {
  'DESCRIPTOR' : _USUARIO,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatsito.Usuario)
  })
_sym_db.RegisterMessage(Usuario)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatsito.Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)

Confirmacion = _reflection.GeneratedProtocolMessageType('Confirmacion', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMACION,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatsito.Confirmacion)
  })
_sym_db.RegisterMessage(Confirmacion)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatsito.Empty)
  })
_sym_db.RegisterMessage(Empty)



_BROADCAST = _descriptor.ServiceDescriptor(
  name='Broadcast',
  full_name='chatsito.Broadcast',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=162,
  serialized_end=496,
  methods=[
  _descriptor.MethodDescriptor(
    name='Enviar',
    full_name='chatsito.Broadcast.Enviar',
    index=0,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_CONFIRMACION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Recibir',
    full_name='chatsito.Broadcast.Recibir',
    index=1,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Conectar',
    full_name='chatsito.Broadcast.Conectar',
    index=2,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_CONFIRMACION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Conectados',
    full_name='chatsito.Broadcast.Conectados',
    index=3,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Enviados',
    full_name='chatsito.Broadcast.Enviados',
    index=4,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Desconectar',
    full_name='chatsito.Broadcast.Desconectar',
    index=5,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_CONFIRMACION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROADCAST)

DESCRIPTOR.services_by_name['Broadcast'] = _BROADCAST

# @@protoc_insertion_point(module_scope)
